/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("java")
    id("com.vaadin") version "24.3.7"
    id("io.quarkus") version "3.2.11.Final"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://delivery.instana.io/artifactory/int-maven-instana-private-virtual/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation(enforcedPlatform("io.quarkus.platform:quarkus-bom:3.2.11.Final"))
    implementation(enforcedPlatform("com.vaadin:vaadin-bom:24.3.7"))
    implementation("com.vaadin:vaadin-quarkus-extension:24.3.7")
}

group = "org.acme"
version = "1.0-SNAPSHOT"
description = "base-starter-flow-quarkus"



tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
